#!/usr/bin/env bash
# configures a brand new Ubuntu machine

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Holberton School" | sudo tee /var/www/html/index.html

otherdefault="/etc/nginx/sites-enabled/default"
location="\\\tadd_header X-Served-By \$hostname;"
sudo sed -i "$location" "$otherdefault"
sudo service nginx restart