#!/usr/bin/env bash
# Install your load balancer

apt-get update
apt-get -y install haproxy

sed -i -e '$ afrontend http_front \n\tbind *:80 \
\tmode http \
\tdefault_backend http_rear \
\nbackend http_rear \
\tbalance		roundrobin \
\tserver 1594-web-01		35.237.217.126:80 check \
\tserver 1594-web-02		35.229.75.225:80 check' /etc/haproxy/haproxy.cfg

service restart haproxy