#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
index=0
while ((index < 10))
do  
    echo "Holberton School"
    ((index++))
    if ((index == 9))
    then
        echo "Hi"    
    fi
done