#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
index=1
while ((index <= 10))
do  
    if ((index == 4))
    then
        echo "bad luck"
    elif ((index == 8))
    then
        echo "good lock"
    else
        echo "Holberton School"
    fi
((index++))
done