#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
index=0
while ((index < 10))
do  
    echo "Holberton School"
    ((index++))
    if ((index == 4))
    then
        echo "bad luck"
    elif ((index == 8))
    then
        echo "good luck"
    fi
done