#!/usr/bin/env bash
#Run Nginx as Nginx
sed -i -e 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i .e 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2 sudo service nginx restart
